version: '3'

services:

  mysqldb:
    image: mysql
    network_mode: host
    # ports:
    #   - "3306:3306"
    volumes:
      - /var/lib/docker/volumes/demoevent/_data/mysqldb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@123
